// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwTR8CmhyNO3GypwNgKg9_1uf2yrJUZM',
    appId: '1:268684001967:web:febb705a12a543af454a5a',
    messagingSenderId: '268684001967',
    projectId: 'intern-todo-ddb9b',
    authDomain: 'intern-todo-ddb9b.firebaseapp.com',
    storageBucket: 'intern-todo-ddb9b.firebasestorage.app',
    measurementId: 'G-GKEXTG112M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bKRpoW1eCBy-E1A9cr7XvDI_5XDOHtA',
    appId: '1:268684001967:android:0ee56431f576431f454a5a',
    messagingSenderId: '268684001967',
    projectId: 'intern-todo-ddb9b',
    storageBucket: 'intern-todo-ddb9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDRS-uSifvOCQCp0mtexoRDL5WKIkPh8',
    appId: '1:268684001967:ios:94ddf23a013018a2454a5a',
    messagingSenderId: '268684001967',
    projectId: 'intern-todo-ddb9b',
    storageBucket: 'intern-todo-ddb9b.firebasestorage.app',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDRS-uSifvOCQCp0mtexoRDL5WKIkPh8',
    appId: '1:268684001967:ios:94ddf23a013018a2454a5a',
    messagingSenderId: '268684001967',
    projectId: 'intern-todo-ddb9b',
    storageBucket: 'intern-todo-ddb9b.firebasestorage.app',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwTR8CmhyNO3GypwNgKg9_1uf2yrJUZM',
    appId: '1:268684001967:web:56aa1776f10cae95454a5a',
    messagingSenderId: '268684001967',
    projectId: 'intern-todo-ddb9b',
    authDomain: 'intern-todo-ddb9b.firebaseapp.com',
    storageBucket: 'intern-todo-ddb9b.firebasestorage.app',
    measurementId: 'G-E7FX5VKT2F',
  );

}