name: todos
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.4.0
  riverpod: ^2.4.0
  uuid: ^4.5.1
  firebase_core: ^3.15.1

dev_dependencies:
  freezed: ^2.4.1
  build_runner: ^2.4.6
  custom_lint: ^0.7.3
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.4.0
  json_serializable:
  cloud_firestore: ^5.6.11
  firebase_core: ^3.10.0
flutter:
  uses-material-design: true
